feat!: add v2 conversion command
web3-storage/pieces pull request #5
Opened 2023-11-22 18:23 UTC by vasco-santos

Per feedback on https://github.com/web3-storage/w3filecoin-infra/pull/80#issuecomment-1823011924 adds conversion command.

Note that needed to upgrade libs that generate PieceCIDv2 now, but will also get a separate PR for it individually to go first

2023-11-22 21:01 UTC, alanshaw requested changes

2023-11-22 21:01 UTC, alanshaw commented on src/v2.js
> +    throw new Error(`PieceCIDv1 received ${cidStr} is not a valid CID`)
Use `exit` here also?

2023-11-22 21:01 UTC, alanshaw commented on src/v2.js
> +  const logSize = opts['log-size'] ? Number(opts['log-size']) : undefined
Should we be using `parseInt` here? Or at least checking we got a positive integer?

2023-11-22 21:01 UTC, alanshaw commented on src/v2.js
> +  if (!height && !logSize) {
Can `height` or `logSize` be zero? If yes then this should be a null/undefined check.

2023-11-22 21:01 UTC, alanshaw commented on src/v2.js
> +      log2PieceSizeToHeight(Number(logSize))
Don't need to cast again here right?

```suggestion
      log2PieceSizeToHeight(logSize)
```

2023-11-22 21:01 UTC, alanshaw commented on cli.js
> +cli.command('v2 [pieceCid]', 'convert PieceCIDv1 to PieceCIDv2')
It is required right?

```suggestion
cli.command('v2 <pieceCid>', 'convert PieceCIDv1 to PieceCIDv2')
```

2023-11-23 12:39 UTC, vasco-santos commented on src/v2.js
> +  if (!height && !logSize) {
by the minimum size of a piece no

2023-11-23 13:18 UTC, alanshaw approved these changes

2023-11-23 15:36 UTC, merged